### ISSUE TITLE
Does piknik -genkeys omit something for the server?

### ISSUE THREAD

**Issue by jpmens** [jedisct1/piknik#2]
Thank you for creating `piknik`: this is a grand idea!

`piknik 0.3` precompiles binaries from releases/. I run

```
piknik -genkeys
```

and copy the section marked _for a server_ to the server, and the section marked _client_ to a client. If I then launch the server (`piknik -server`) and use `pkc` on the client, the client says:

```bash
echo hello | pkc
2016/07/23 16:37:06 EOF

pkp
2016/07/23 16:37:22 unexpected EOF
```

If, however, I use the "hybrid configuration" from `-genkeys` on the server, it works.

The following contains my `~/.piknik.toml` on the server (no worries: I'll throw this away later :-) 

```toml
# Hybrid configuration

#Connect   = "192.168.1.81:8075"	# Edit appropriately
#Listen    = "0.0.0.0:8075"	# Edit appropriately
#Psk       = "0f51549a6c18c18a48695939f75e231de755543e18d08c2b5698d74515eb40c1"
#SignPk    = "670ab3a47bc63ca4c55f0e507fab249576ec5fc2ab9af4ddfdad96a417feb932"
#SignSk    = "b6dea70cdd36b28b2dbe9bfb24844fa1a7e534f30af7231c6dbdd0c40b5a3f64"
#EncryptSk = "b8a1a03b73906c0afdc7036c902d604fecd3e866cac05cb55e649a1d6cc33343"

# Configuration for a server

Listen = "0.0.0.0:8075"	# Edit appropriately
Psk    = "0f51549a6c18c18a48695939f75e231de755543e18d08c2b5698d74515eb40c1"
SignPk = "670ab3a47bc63ca4c55f0e507fab249576ec5fc2ab9af4ddfdad96a417feb932"
```

Leaving just bottom part: fails
Using just top part: succeeds
